### PR TITLE
Update community.json

### PR DESCRIPTION
**Pull request by linusschrab**

### CODE REVIEW

**Comment by ngwese** [comment]
@dndrks just a heads up, i see the thread on lines so changing the url is understood to be intentional. one potential downside of changing the url to the git repo is the existing installs on devices will have to be deleted then reinstalled. 

maiden only uses the url in the catalog at install time when the source is a git repo.

**Comment by dndrks** [comment]
mmmm gotcha, thank you for the heads up @ngwese  -- i guess the alternative is just removing less concepts and @linusschrab submits a new entry altogether. that seems more workable, yeah?

also, @linusschrab , you forgot to include your name in the byline ;)

**Comment by linusschrab** [comment]
@ngwese / @dndrks - Did we land on a solution for this? I'd be happy to delete this and create a new pull request for LC3. Just let me know what works best.

**Comment by dndrks** [comment]
i think that’ll do it :) i’ll just delete the original

**Comment by linusschrab** [comment]
found a better solution to this.

**Pull request closed without merging**
