### PR TITLE
Update community.json

### PR DESCRIPTION
**Pull request by linusschrab**
updated project URL for LC3 to dan's repo.

### CODE REVIEW

**Review by ngwese — COMMENTED** [review]
one note of caution when changing urls to the code itself is that people will not pick up that change unless they delete their current installation and reinstall.

**Comment by linusschrab** [comment]
dan asked me to update the url to let him take control of the repo again and i guess make lc3 -> lc. let's wait and see what he responds when he's back online.

**Comment by dndrks** [comment]
woop, didn't see this, apologies!
i'm in favor of merging our authorship over the existing `less_concepts` script + repo, which should not necessitate deletion! https://github.com/monome/norns-community/pull/199

**Comment by dndrks** [comment]
AHA fixed it, just made a new organization under `vicimity-dndrks`!!

**Pull request closed without merging**
