### PR TITLE
New format

### LINKED ISSUE #245: format, cleanup, sort
a few of us are working towards migrating the `norns.community` wiki to a much lighter, automatically generated static site. the primary goal is to lower the workload for contributors and avoid some of the maintenance issues we've had with the current overspec'd wikijs system.

the current progress on the static site generator is here: https://github.com/monome-community/norns-community

TODO to facilitate the above

1. we need to standardize the "author" field. currently it's (mostly) of the form `"Brian Crabtree (tehn)"`. we need this to be just `"tehn"`.
2. some author tags are collaborations. these need to be rewritten as a JSON list ie `["tehn", "zebra"]`
3. the full catalog needs to be run through a sort by `project_name`

(the reason we're doing this is to make url-friendly author names, to facilitate seeing a list of scripts written by an author)

### PR DESCRIPTION
**Pull request by tehn**
fixes #245

~~DO NOT MERGE: i have not yet tested this with maiden and am concerned that the datatype variation of collab projects will cause breakage.~~

1. url-safe (one word) `author` field
2. ~~collabs are a list, not a string~~

thanks to @p3r7 for the initial scrub with python, which i hand-cleaned and corrected with vim macros

### CODE REVIEW

**Comment by p3r7** [comment]
just realized there is this script that have special characters in its name and got messed up

https://github.com/monome/norns-community/pull/246/files#diff-7531405d092188437c0fbe32189e6134b93e90bb098d3e0ff45b9192d70c7d57R1178

**Comment by tehn** [comment]
@ngwese i'm having a strangely difficult time changing the catalog source on-device, as it seems like i should just be able to change sources/community.json to the path of this branch, but on refresh maiden is failing. i'm not familiar with maiden debugging, but can dig in. searching the codebase, i'm not sure `author` is even really used, except that its type is getting checked in the schema (obviously would need to be changed).

i might just punt on this to avoid disturbing the maiden codebase, and have collabs be listed as a string with spaces ie `tehn ngwese zebra` and then let the SSG python deal with parsing this instead of having json lists.

**Comment by tehn** [comment]
ok, made changed back to just a string. this should be functionally non-impactful, so i'm going to merge.

**Comment by ngwese** [comment]
@tehn - changing the catalog format such that `authors` is a list instead of a string would require changing `maiden` itself. The json schema which the GH CI pipeline is enforcing is there to ensure that the JSON objects match the shape of some structures which are generated directly from the JSON data via Go's serialization/deserialization support: https://github.com/monome/maiden/blob/main/pkg/catalog/catalog.go#L15

**Pull request merged**
