### PR TITLE
adds "combos" collection

### PR DESCRIPTION
**Pull request by justmat**
also changed my attributions from Matthew to Mat.

### CODE REVIEW

**Comment by justmat** [comment]
Any way we could get this merged? Assuming I formatted everything correctly 😅 @tehn

**Comment by ngwese** [comment]
Apologies for the delay. The notification didn’t come through.

**Comment by tehn** [comment]
also apologies here, i forgot to watch this repo 😬

**Comment by justmat** [comment]
No apologies necessary! Thanks for the merge @ngwese

**Pull request merged**
